# Generated by Django 5.2.4 on 2025-07-31 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesorregiao',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('sigla', models.TextField(max_length=2)),
                ('nome', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RegiaoImediata',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegiaoIntermediaria',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Microrregiao',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.TextField(max_length=20)),
                ('mesorregiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibge.mesorregiao')),
            ],
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.TextField(max_length=50)),
                ('microrregiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibge.microrregiao')),
                ('regiao_imediata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibge.regiaoimediata')),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('sigla', models.TextField(max_length=50)),
                ('nome', models.TextField()),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibge.regiao')),
            ],
        ),
        migrations.AddField(
            model_name='regiaoimediata',
            name='regiao_intermediaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibge.regiaointermediaria'),
        ),
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('sigla', models.TextField(max_length=2)),
                ('nome', models.TextField(max_length=20)),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibge.regiao')),
            ],
        ),
        migrations.AddField(
            model_name='regiaointermediaria',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibge.uf'),
        ),
        migrations.AddField(
            model_name='mesorregiao',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibge.uf'),
        ),
        migrations.CreateModel(
            name='Distritos',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.TextField(max_length=50)),
                ('mesorregiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibge.mesorregiao')),
                ('microrregiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibge.microrregiao')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibge.municipios')),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibge.regiao')),
                ('regiao_imediata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibge.regiaoimediata')),
                ('regiao_intermediaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibge.regiaointermediaria')),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibge.uf')),
            ],
        ),
    ]
