# Generated by Django 5.2.4 on 2025-07-31 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='microrregiao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ibge.microrregiao'),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='regiao_imediata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ibge.regiaoimediata'),
        ),
    ]
