# Generated by Django 5.2.4 on 2025-07-31 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibge', '0002_alter_municipios_microrregiao_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='municipios',
            index=models.Index(fields=['nome'], name='ibge_munici_nome_863eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='municipios',
            index=models.Index(fields=['microrregiao'], name='ibge_munici_microrr_0626aa_idx'),
        ),
        migrations.AddIndex(
            model_name='municipios',
            index=models.Index(fields=['regiao_imediata'], name='ibge_munici_regiao__2b6ce1_idx'),
        ),
    ]
