# Generated by Django 5.2.4 on 2025-08-01 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibge', '0003_municipios_ibge_munici_nome_863eb8_idx_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Distritos',
            new_name='Distrito',
        ),
        migrations.RenameModel(
            old_name='Estados',
            new_name='Estado',
        ),
        migrations.RenameModel(
            old_name='Municipios',
            new_name='Municipio',
        ),
        migrations.AlterModelOptions(
            name='distrito',
            options={'verbose_name': 'Distrito', 'verbose_name_plural': 'Distritos'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'verbose_name': 'Município', 'verbose_name_plural': 'Municípios'},
        ),
        migrations.RenameIndex(
            model_name='municipio',
            new_name='ibge_munici_nome_3c52fd_idx',
            old_name='ibge_munici_nome_863eb8_idx',
        ),
        migrations.RenameIndex(
            model_name='municipio',
            new_name='ibge_munici_microrr_6690b9_idx',
            old_name='ibge_munici_microrr_0626aa_idx',
        ),
        migrations.RenameIndex(
            model_name='municipio',
            new_name='ibge_munici_regiao__d2571e_idx',
            old_name='ibge_munici_regiao__2b6ce1_idx',
        ),
    ]
