# Generated by Django 5.2.4 on 2025-08-01 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibge', '0004_rename_distritos_distrito_rename_estados_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrito',
            name='mesorregiao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ibge.mesorregiao'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='microrregiao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ibge.microrregiao'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='regiao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ibge.regiao'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='regiao_imediata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ibge.regiaoimediata'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='regiao_intermediaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ibge.regiaointermediaria'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='uf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ibge.uf'),
        ),
    ]
