# Generated by Django 5.2.4 on 2025-08-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('cnpj_basico', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('rasao_social', models.TextField(max_length=255)),
                ('natureza_juridica', models.IntegerField()),
                ('clasificacao_do_responsavel', models.IntegerField()),
                ('capital_social', models.IntegerField()),
                ('porte', models.IntegerField()),
                ('ente_federativo_responsavel', models.TextField()),
            ],
        ),
    ]
