# Generated by Django 5.2.4 on 2025-08-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='ente_federativo_responsavel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
